import { IParticipant } from "../interfaces/IParticipant";

export const extractNeuralParametersFromRiotPayload = (participant: IParticipant) => {
  return {
    assists: participant.assists,
    baronKills: participant.baronKills,
    // bountyLevel: participant.boun,
    championId: participant.championId,
    damageDealtToBuildings: participant.damageDealtToBuildings,
    damageDealtToObjectives: participant.damageDealtToObjectives,
    damageDealtToTurrets: participant.damageDealtToTurrets,
    damageSelfMitigated: participant.damageSelfMitigated,
    deaths: participant.deaths,
    dragonKills: participant.dragonKills,
    doubleKills: participant.doubleKills,
    firstBloodAssist: participant.firstBloodAssist,
    firstBloodKill: participant.firstBloodKill,
    // firstTowerAssist: participant.first,
    goldEarned: participant.goldEarned,
    goldSpent: participant.goldSpent,
    // individualPosition: participant.individualPosition,
    kills: participant.kills,
    largestKillingSpree: participant.largestKillingSpree,
    largestMultiKill: participant.largestMultiKill,
    longestTimeSpentLiving: participant.longestTimeSpentLiving,
    magicDamageDealt: participant.magicDamageDealt,
    magicDamageDealtToChampions: participant.magicDamageDealtToChampions,
    magicDamageTaken: participant.magicDamageTaken,
    neutralMinionsKilled: participant.neutralMinionsKilled,
    nexusKills: participant.nexusKills,
    nexusLost: participant.nexusLost,
    nexusTakedowns: participant.nexusTakedowns,
    objectivesStolen: participant.objectivesStolen,
    pentaKills: participant.pentaKills,
    physicalDamageDealt: participant.physicalDamageDealt,
    // physicalDamageDealtToChampions: participant.phy,
    physicalDamageTaken: participant.physicalDamageTaken,
    teamId: participant.teamId,
    totalDamageDealt: participant.totalDamageDealt,
    totalDamageDealtToChampions: participant.totalDamageDealtToChampions,
    totalDamageShieldedOnTeammates: participant.totalDamageShieldedOnTeammates,
    totalDamageTaken: participant.totalDamageTaken,
    totalHeal: participant.totalHeal,
    totalHealsOnTeammates: participant.totalHealsOnTeammates,
    totalMinionsKilled: participant.totalMinionsKilled,
    // totalTimeCCDealt: participant.total,
    totalTimeSpentDead: participant.totalTimeSpentDead,
    totalUnitsHealed: participant.totalUnitsHealed,
    tripleKills: participant.tripleKills,
    quadraKills: participant.quadraKills,
    trueDamageDealt: participant.trueDamageDealt,
    trueDamageDealtToChampions: participant.trueDamageDealtToChampions,
    trueDamageTaken: participant.trueDamageTaken,
    turretKills: participant.turretKills,
    // turretTakedowns: participant.turretTakendowns,
    // turretsLost: participant.turretLost,
    unrealKills: participant.unrealKills,
    visionScore: participant.visionScore,
    visionWardsBoughtInGame: participant.visionWardsBoughtInGame,
    wardsKilled: participant.wardsKilled,
    // wardsPlaced: participant.wards,
    win: participant.win
  }
}